DIALOGS = [
            "",
            "La Torre de Icesium se desmoronaba. Algo esta mal.",
            "La Torre de Icesium se desmoronaba. Algo esta mal.",
            "La Torre de Icesium se desmoronaba. Algo esta mal.",
            "La Torre de Icesium se desmoronaba. Algo esta mal.",
            "La Torre de Icesium se desmoronaba. Algo esta mal.",
            "La Torre de Icesium se desmoronaba. Algo esta mal.",
            "",
            "Las runas protectoras se apagaron y la sala era un caos.",
            "Las runas protectoras se apagaron y la sala era un caos.",
            "Las runas protectoras se apagaron y la sala era un caos.",
            "Las runas protectoras se apagaron y la sala era un caos.",
            "Las runas protectoras se apagaron y la sala era un caos.",
            "",
            "Angela, la hechicera, invoca el conjuro \"Seguimiento\" que hizo temblar la torre.",
            "Angela, la hechicera, invoca el conjuro \"Seguimiento\" que hizo temblar la torre.",
            "Angela, la hechicera, invoca el conjuro \"Seguimiento\" que hizo temblar la torre.",
            "Angela, la hechicera, invoca el conjuro \"Seguimiento\" que hizo temblar la torre.",
            "Angela, la hechicera, invoca el conjuro \"Seguimiento\" que hizo temblar la torre.",
            "",
            "Las puertas se cerraron a tu espalda. No hay vuelta atras.",
            "Las puertas se cerraron a tu espalda. No hay vuelta atras.",
            "Las puertas se cerraron a tu espalda. No hay vuelta atras.",
            "Las puertas se cerraron a tu espalda. No hay vuelta atras.",
            "Las puertas se cerraron a tu espalda. No hay vuelta atras.",
            "",
            "Del espejo emerge una sombra. Alguien —o algo— viene por por ti.",
            "Del espejo emerge una sombra. Alguien —o algo— viene por por ti.",
            "Del espejo emerge una sombra. Alguien —o algo— viene por por ti.",
            "Del espejo emerge una sombra. Alguien —o algo— viene por por ti.",
            "Del espejo emerge una sombra. Alguien —o algo— viene por por ti.",
            "Del espejo emerge una sombra. Alguien —o algo— viene por por ti.",
            "",
        ]